[package]
name = "aoc_2024b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.94"
location-macros = "0.1.2"

[features]
default = ["part-one", "part-two"]
part-one = []
part-two = []
